version: '3.8'

services:
  newsbot:
    build: .
    container_name: telegram-newsbot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./rss-feeds.json:/app/rss-feeds.json
      - ./.env:/app/.env
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - GIT_REPO_URL=https://github.com/thanghnm49/NewsBot.git
      - GIT_BRANCH=main

