version: '3.8'

services:
  newsbot:
    build: .
    container_name: telegram-newsbot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./rss-feeds.json:/app/rss-feeds.json
      - ./index.js:/app/index.js
      - ./package.json:/app/package.json
    environment:
      - NODE_ENV=production

